INSERT INTO `{CHC_TABLE_ACCESS}` ( timestamp, typ ) VALUES ( {TIMESTAMP}, 'tageszeit_wochentag_start' );
INSERT INTO `{CHC_TABLE_ACCESS}` ( typ ) VALUES ( 'tageszeit' );
INSERT INTO `{CHC_TABLE_ACCESS}` ( typ ) VALUES ( 'wochentag_1_Mon' );
INSERT INTO `{CHC_TABLE_ACCESS}` ( typ ) VALUES ( 'wochentag_2_Tue' );
INSERT INTO `{CHC_TABLE_ACCESS}` ( typ ) VALUES ( 'wochentag_3_Wed' );
INSERT INTO `{CHC_TABLE_ACCESS}` ( typ ) VALUES ( 'wochentag_4_Thu' );
INSERT INTO `{CHC_TABLE_ACCESS}` ( typ ) VALUES ( 'wochentag_5_Fri' );
INSERT INTO `{CHC_TABLE_ACCESS}` ( typ ) VALUES ( 'wochentag_6_Sat' );
INSERT INTO `{CHC_TABLE_ACCESS}` ( typ ) VALUES ( 'wochentag_7_Sun' );
INSERT INTO `{CHC_TABLE_ACCESS}` ( timestamp, typ, erster_eintrag ) VALUES ( {TIMESTAMP_THIS_DAY}, 'tag', 1 );
INSERT INTO `{CHC_TABLE_ACCESS}` ( timestamp, typ, erster_eintrag ) VALUES ( {TIMESTAMP_THIS_WEEK}, 'kw', 1 );
INSERT INTO `{CHC_TABLE_ACCESS}` ( timestamp, typ, erster_eintrag ) VALUES ( {TIMESTAMP_THIS_MONTH}, 'monat', 1 );
INSERT INTO `{CHC_TABLE_ACCESS}` ( timestamp, typ, erster_eintrag ) VALUES ( {TIMESTAMP_THIS_YEAR}, 'jahr', 1 );



INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_aufloesungen', '10');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('admin_name', '{ADMIN_NAME}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('admin_passwort', '{ADMIN_PASSWORD}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('modus_zaehlsperre', 'intervall');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('blockzeit', '86400');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('user_online_fuer', '300');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('log_eintraege_loeschen_nach:wert_in_sek', '2421972');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('log_eintraege_loeschen_nach:einheit_administration', 'd');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('anordnung_log_eintraege', 'ASC');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('anzahl_pro_logseite', '100');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_referrer', '10');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_refdomains', '10');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('show_online_users_ip', '2');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_seiten', '20');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_user_agents', '10');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_sprachen', '10');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_hosts_tlds', '10');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_laender', '10');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_all_lists', '1000');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_suchwoerter', '10');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_suchphrasen', '10');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_downloads', '10');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_hyperlinks', '10');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_latest', '10');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_top', '10');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_host_tlds', '20');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_suchmaschinen', '10');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_browser', '20');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_os', '20');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_anzahl_robots', '20');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('db_aufraeumen_nach', '86400');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('zeitzone', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('dst', '{DST}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('lang', '{LANGUAGE}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('lang_administration', '{LANGUAGE}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('seitenstatistik_titel_suche', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('status_logs', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('status_referrer', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('status_user_agents', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('status_clh', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('status_seiten', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('status_einstiegs_ausgangsseiten', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('status_aufloesungen', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('status_access', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('status_suchmaschinen_und_suchwoerter', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('status_suchphrasen', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('status_js', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('script_version', '{SCRIPT_VERSION}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('block_robots', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('statistiken_login_erforderlich', 'index:all_lists;');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('blacklist_user_agents', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('blacklist_referrers', '%q=www.%+sex%.%');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('blacklist_pages', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('blacklist_ips', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('blacklist_hosts', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('exclusion_list_user_agents', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('exclusion_list_referrers', '{EXCLUSION_LIST_REFERRERS}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('exclusion_list_keywords', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('exclusion_list_search_phrases', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('exclusion_list_pages', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('exclusion_list_screen_resolutions', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('hideout_list_pages', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('hideout_list_screen_resolutions', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('hideout_list_keywords', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('hideout_list_search_phrases', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('hideout_list_referrers', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('hideout_list_user_agents', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('referrer_kuerzen_nach', '27');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('referrer_kuerzungszeichen', '...');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_latest_x', '30');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_top_x', '30');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_referrer', '30');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_refdomains', '30');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_suchwoerter', '30');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_suchphrasen', '30');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_seite_online_users', '30');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_seiten', '30');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_browser', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_user_agents', '30');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_aufloesungen', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_downloads', '30');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_os', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_robots', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_laender', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_sprachen', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_hosts_tlds', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_all_lists', '50');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('wordwrap_suchmaschinen', '30');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('hideout_list_browsers', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('hideout_list_os', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('hideout_list_robots', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('user_agents_kuerzen_nach', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('user_agents_kuerzungszeichen', '...');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('fremde_URLs_verlinken', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('hideout_list_referring_domains', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('gast_name', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('gast_passwort', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('admin_blocking_cookie', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('exclusion_list_search_engines', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('hideout_list_search_engines', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('default_counter_visibility', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('referrer_query_string_entfernen', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('seiten_query_string_bereinigung_variablen', 'latest; top; sort_by; sort_order; distr_type; distr_of; d_day; d_month; d_year; d_type; m_month; m_year; m_type; w_month; w_year; w_type; y_year; y_type; l_last; l_type; lang; type; clh; homepage_id; kp; p; month; p_month; d_month; h_month; ref_month; refdom_month; kp_month; se_month; b_month; os_month; r_month; clh_month; res_month; {SESSION_NAME}; ');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('seiten_query_string_bereinigung_modus', 'ohne');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_pseudo', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_access', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_referrer', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_user_agents', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_browser', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_os', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_robots', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_seiten', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_laender', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_sprachen', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_hosts_tlds', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_suchmaschinen', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_suchwoerter_suchphrasen', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_aufloesungen', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_javascript', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('timestamp_start_verweisende_domains', '{TIMESTAMP}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('zeige_seitentitel', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('logdaten_zeige_seitentitel', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('default_homepage_url', '{DEFAULT_HOMEPAGE_URL}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('homepages_urls', '1 => default_homepage_url; ');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('default_counter_url', '{DEFAULT_COUNTER_URL}');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('counter_urls', '1 => default_counter_url; ');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('aktiviere_seitenverwaltung_von_mehreren_domains', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('seitenstatistik:_zeige_homepages_getrennt', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('regelmaessiges_loeschen:user_agents:werte', '1;8640000');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('regelmaessiges_loeschen:user_agents:aktiviert', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('regelmaessiges_loeschen:referrer:werte', '1;8640000');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('regelmaessiges_loeschen:referrer:aktiviert', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('regelmaessiges_loeschen:verweisende_domains:werte', '1;8640000');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('regelmaessiges_loeschen:verweisende_domains:aktiviert', '0');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('darstellungsart_balkendiagramme_zugriffsstatistiken', 'relativ');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('homepage_charset', 'ISO-8859-1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('js_gleichwertige_homepage_urls', '');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('min_jscode_version', '3.0.0Beta8');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('min_zeichenlaenge_suchwoerter_suchphrasen', '3');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('counterstatus_statistikseiten', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('robots_von_js_stats_ausschliessen', '1');
INSERT INTO `{CHC_TABLE_CONFIG}` VALUES ('php_self_oder_request_uri', 'REQUEST_URI');




INSERT INTO `{CHC_TABLE_DATA}`
	( `heute_timestamp`, `max_online:timestamp`, `max_besucher_pro_tag:timestamp`, `max_seitenaufrufe_pro_tag:timestamp`,  `durchschnittlich_pro_tag:timestamp`, `timestamp_letztes_db_aufraeumen` )
	VALUES ( {TIMESTAMP}, {TIMESTAMP}, {TIMESTAMP}, {TIMESTAMP}, {TIMESTAMP}, {TIMESTAMP} );